# Generated by Django 5.1.1 on 2024-12-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiny1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('text1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tiny2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('text1', models.TextField()),
            ],
        ),
    ]
