# Generated by Django 5.1.1 on 2024-12-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tiny1_tiny2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Go',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
                ('nomi', models.CharField(max_length=90)),
                ('tugma', models.CharField(max_length=90)),
            ],
        ),
    ]
