# Generated by Django 5.1.1 on 2024-12-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_go'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
                ('narx', models.IntegerField()),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('tugma', models.CharField(max_length=90)),
            ],
        ),
    ]
