# Generated by Django 5.1.1 on 2024-12-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_feat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
